services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: coin-auto-trading-app
    env_file:
      - .env.prod
    depends_on:
      - postgres
    restart: unless-stopped

  postgres:
    image: postgres:16
    container_name: coin-postgres-prod
    env_file:
      - .env.prod
    volumes:
      - postgres_prod_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_prod_data: